### PR TITLE
Add dusk and some tests

### PR DESCRIPTION
**Pull request by timberwoof**
Dusk works. Most of the tests work. 

RegisterTest.php fails. For some reason it fails to select  the state-province or enter the password-confirm. The HTML code I'm trying to pick is there in comments for cases that fail and similar cases that work. I don't see the difference.

### CODE REVIEW

**Review by dweinerATL — COMMENTED** [review]
Does the Dusk harness spin up a webserver on localhost, or are you basing those calls on your local setup?

**Comment by timberwoof** [comment]
Dusk does not afaik spin up its own webserver; it expects whatever server is specified in its configuration to be already running.

**Comment by dweinerATL** [comment]
Ok, I'll have to figure out how to get CircleCI to spin up a webserver so we can test that :)

**Comment by dweinerATL** [comment]
Oh, something else to keep in mind -- each individual developer may not have MEDUSA Core set as the default, so while using 127.0.0.1 is entirely correct, it's not 100%.  I would modify those tests to pull the value of `APP_URL` for those tests.  See https://laravel.com/docs/6.x/helpers#method-url

**Pull request merged**
